server.port=8081
spring.application.name=ISS-Project
spring.datasource.url=${DATABASE_URL}
#spring.datasource.url="jdbc:postgresql://neondb_owner:npg_kPyQn7TMmXw9@ep-round-violet-apn95700-pooler.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.level.root=INFO
logging.level.org.example.issproject=INFO
logging.level.org.springframework.security=INFO

jwt.secret=${JWT_SECRET}
cloudinary.cloud_name=${CL_NAME}
cloudinary.api_key=${CL_AP_KEY}
cloudinary.api_secret=${CL_AP_SEC}

metered.secret.key=${METERED_SECRET_KEY}