server.port=8081
spring.application.name=ISS-Project
spring.datasource.url=jdbc:postgresql://localhost:5432/discord_clone
spring.datasource.username=postgres
spring.datasource.password=raul
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.level.root=INFO
logging.level.org.example.issproject=INFO
logging.level.org.springframework.security=INFO

jwt.secret=billy12345678900987654321billyasdfghjklzxcvbnm
cloudinary.cloud_name=dxuak2lkv
cloudinary.api_key=424156324362195
cloudinary.api_secret=sKUinPFpqvA6IeG2oc0_Q4tsJf0